#### Creating data for sequential choice models
The series of models I plan to use in my thesis project, inspired by habitat-selection functions from movement ecology, use environmental covariates of available resources (e.g., distance from current location, turning angle from previous bearing angle, size/point value, etc.) to predict whether a resource will be chosen next. By specifying a series of models containing different parameters, I will fit different cognitive heuristic strategies to human sequential choice data and determine parameters of significance to the foraging strategies of participants.

To start, I must take existing foraging data in the form of logs of collected objects during play and expand it out to include the covariates of interest of all available objects. This data needs to also reflect the removal and reintroduction of collected objects during the course of play.

In [1]:
# import libraries
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
# read in simulation results
player_paths = pd.read_csv(
    '../../data/clean_datasets/clean_location_data.csv'
)

player_forages = pd.read_csv(
    '../../data/clean_datasets/imputed_forage_data.csv'
)

# clean up
# reset index
player_paths.index = [*range(len(player_paths))]
player_forages.index = [*range(len(player_forages))]

# subset cols, remove old x and y and rename imputed x,y to x,y
player_forages = player_forages.iloc[:, [*range(0, 4), *range(6, 9)]]

player_forages.rename(columns={
    'new_x': 'x',
    'new_y': 'y'
}, inplace=True)

# read in obj locs
all_lvls_coco_locs = pd.read_csv(
    '../../data/level_arrangements/all_levels_arrangements.csv'
)

In [3]:
player_forages.head()

   subject  level  obj_ID  point_value     x     y         time
0    46986      1      58            2  -6.5 -15.0  1542.796997
1    46986      1      59            2 -10.0 -15.0  1543.081055
2    46986      1      56            2 -12.5 -17.5  1543.463989
3    46986      1      60            2 -15.0 -15.0  1543.496948
4    46986      1      53            2 -15.0 -20.0  1543.729004

##### Adding covariates and all available objects
The two covariates of interest needed to be added to this expanded data set are distance from current location and turning angle

In [4]:
# distance matrices store distances between coconuts
def create_distance_matrices(obj_locs=pd.DataFrame):

    # create list for levels
    dist_matrix_list = []

    # for each level, create matrix of all distances
    for level in range(0, 10):
        # filter for this level
        level_locs = obj_locs[obj_locs.level == level+1]

        # reset index for consistent indexing
        level_locs.index = [*range(0, len(level_locs))]

        # create empty matrix
        level_m = np.zeros((len(level_locs), len(level_locs)), dtype=float)

        # fill this level's matrix
        for i in range(0, len(level_locs)):
            for j in range(0, len(level_locs)):
                # check if same location
                if i == j:
                    level_m[i, j] = 0  # set to zero, save computation
                else:
                    # calc distance and store in matrix
                    level_m[i, j] = np.sqrt(
                        np.pow(level_locs.x[i]-level_locs.x[j], 2) +
                        np.pow(level_locs.y[i]-level_locs.y[j], 2)
                    )

        # add to list
        dist_matrix_list.append(level_m)

    return dist_matrix_list

In [5]:
d = create_distance_matrices(all_lvls_coco_locs)

In [49]:
# calculate turning angles
def calculate_turning_angles(
    previous_head_angle=float, curr_coco_id=int, lvl_coco_locs=pd.DataFrame
):

    # empty list for angles
    ta_list = []

    # loop through df and calculate each ta
    for coco_id in lvl_coco_locs.obj_ID:
        if coco_id == curr_coco_id:
            # add NA for curr obj
            ta_list.append(pd.NA)
        else:
            ta = np.atan2(
                lvl_coco_locs.iloc[coco_id-1].y -
                lvl_coco_locs.iloc[curr_coco_id-1].y,
                lvl_coco_locs.iloc[coco_id-1].x -
                lvl_coco_locs.iloc[curr_coco_id-1].x
            ) - previous_head_angle

            ta_list.append(ta)

    return ta_list

In [ ]:
# create sliced dfs to work with for testing
slice_df = player_forages[







    (player_forages.subject == player_forages.iloc[0].subject) &







    (player_forages.level == player_forages.iloc[0].level)
]



path_slice_df = player_paths[







    (player_paths.subject == player_forages.iloc[0].subject) &







    (player_paths.level == player_forages.iloc[0].level)







]

lvl_locs = all_lvls_coco_locs[all_lvls_coco_locs.level ==
                              path_slice_df.iloc[0].level]

In [21]:
slice_df.head()

   subject  level  obj_ID  point_value     x     y         time
0    46986      1      58            2  -6.5 -15.0  1542.796997
1    46986      1      59            2 -10.0 -15.0  1543.081055
2    46986      1      56            2 -12.5 -17.5  1543.463989
3    46986      1      60            2 -15.0 -15.0  1543.496948
4    46986      1      53            2 -15.0 -20.0  1543.729004

In [ ]:
# grouped function to find both ta and distances of alternatives
def find_turning_angles_and_distances(
    collection_time=float, path_df=pd.DataFrame, lvl_coco_locs=pd.DataFrame
):

    # find the heading angle

    # slice the path df before collection time
    path_slice = path_df[path_df.time <= collection_time].tail(n=2)

    # get heading angle
    heading_angle = np.atan2(
        path_slice.iloc[1].y - path_slice.iloc[0].y,
        path_slice.iloc[1].x - path_slice.iloc[0].x
    )

    # find turning angles to available obj
    # empty list for angles
    ta_list = [
        np.atan2(
            lvl_coco_locs.iloc[coco-1].y -
            path_slice.iloc[1].y,
            lvl_coco_locs.iloc[coco-1].x -
            path_slice.iloc[1].x
        ) - heading_angle for coco in lvl_coco_locs.obj_ID
    ]

    # find the distances
    dist_list = [
        np.sqrt(
            np.pow(lvl_coco_locs.iloc[coco-1].y -
                   path_slice.iloc[1].y, 2) +
            np.pow(lvl_coco_locs.iloc[coco-1].x -
                   path_slice.iloc[1].x, 2)
        ) for coco in lvl_coco_locs.obj_ID
    ]

    return ta_list, dist_list


# check out how it is working, can compare to plot_forage_path in
# pull_and_clean R script


# tas, dists = find_turning_angles_and_distances(
#     slice_df.iloc[0].time, path_slice_df, lvl_locs)

# # combine into little df with obj ids for viewing
# df = pd.DataFrame({
#     'obj_ID': lvl_locs.obj_ID,
#     'ta': np.cos(tas),
#     'dist': dists
# })

# print(df.sort_values(by='ta', ascending=False).head(n=6))
# print(df.sort_values(by='dist', ascending=True).head(n=6))

    obj_ID        ta       dist
61      62  0.999746  19.792307
60      61  0.999625  16.293388
59      60  0.999219  11.296093
58      59  0.997491   6.303093
63      64  0.989087  13.939397
57      58  0.987424   2.822774
    obj_ID        ta      dist
57      58  0.987424  2.822774
58      59  0.997491  6.303093
64      65  0.809888  7.763142
53      54  0.755850  8.318148
62      63  0.973758  9.024082
55      56  0.948126  9.268045

In [50]:
# neighbors distance
def neighborhood_value(
    curr_coco_id=int, lvl_dist_matrix=list, num_neighbors=int, avail_indices=list
):
    # filter the df for currently available obj and their distances from focal obj
    active_obj_dists = lvl_dist_matrix[curr_coco_id-1][avail_indices]

    return np.sum(np.reciprocal(sorted(active_obj_dists)[1:num_neighbors+1]))

In [ ]:
for subject in player_forages.subject.unique():

    lvls = player_forages[player_forages.subject == subject].level.unique()

    for lvl in lvls:
        print(subject, lvl)

        # subset forage data, path data, matrices, coco locations

        # create empty expansion df

        # loop through collections

        # calculate dist, ta, clst and create expanded row then continue

        # write expansion to disk

46986 1
46986 2
46986 3
46986 4
46986 5
46986 6
46986 7
46986 8
46986 9
46986 10
47192 1
47192 2
47192 3
47192 4
47192 5
47192 6
47192 7
47192 8
47192 9
47192 10
47220 1
47220 2
47220 3
47220 4
47220 5
47220 6
47220 7
47220 8
47220 9
47220 10
47601 1
47601 2
47601 3
47601 4
47601 5
47601 6
47601 7
47601 8
47601 9
47601 10
47835 1
47835 2
47835 3
47835 4
47835 5
47835 6
47835 7
47835 8
47835 9
47835 10
48109 1
48109 2
48109 3
48109 4
48109 5
48109 6
48109 7
48109 8
48109 9
48109 10
48122 1
48122 2
48122 3
48122 4
48122 5
48122 6
48122 7
48122 8
48122 9
48122 10
48262 1
48262 2
48262 3
48262 4
48262 5
48262 6
48262 7
48262 8
48262 9
48262 10
48464 1
48464 2
48464 3
48464 4
48464 5
48464 6
48464 7
48464 8
48464 9
48464 10
48480 1
48480 2
48480 3
48480 4
48480 5
48480 6
48480 7
48480 8
48480 10
48484 1
48484 2
48484 3
48484 4
48484 5
48484 6
48484 7
48484 8
48484 9
48484 10
48486 1
48486 2
48486 3
48486 4
48486 5
48486 6
48486 7
48486 8
48486 9
48486 10
48487 1
48487 2
48487 3
48487 4
48487 5
48487 6
48487 7
48487 8
48487 9
48487 10
48488 1
48488 2
48488 3
48488 4
48488 5
48488 6
48488 7
48488 8
48488 9
48488 10
48490 1
48490 2
48490 3
48490 4
48490 5
48490 6
48490 7
48490 8
48490 9
48490 10
48494 1
48494 2
48494 3
48494 4
48494 5
48494 6
48494 7
48494 8
48494 9
48494 10
48496 1
48496 2
48496 3
48496 4
48496 5
48496 6
48496 7
48496 8
48496 9
48496 10
48497 1
48497 2
48497 3
48497 4
48497 5
48497 6
48497 7
48497 8
48497 9
48497 10
48498 1
48498 2
48498 3
48498 4
48498 5
48498 6
48498 7
48498 8
48498 9
48498 10
48501 1
48501 2
48501 3
48501 4
48501 5
48501 6
48501 7
48501 8
48501 9
48501 10
48504 1
48504 2
48504 3
48504 4
48504 5
48504 6
48504 7
48504 8
48504 9
48508 1
48508 2
48508 3
48508 4
48508 5
48508 6
48508 7
48508 8
48508 9
48508 10
48511 1
48511 2
48511 3
48511 4
48511 5
48511 6
48511 7
48511 8
48511 9
48511 10
48527 1
48527 2
48527 3
48527 4
48527 5
48527 6
48527 7
48527 9
48527 10
48532 1
48532 2
48532 3
48532 4
48532 5
48532 6
48532 7
48532 8
48532 9
48532 10
48538 1
48538 2
48538 3
48538 4
48538 5
48538 6
48538 7
48538 8
48538 9
48538 10
48540 1
48540 2
48540 3
48540 4
48540 5
48540 6
48540 7
48540 8
48540 9
48540 10
48543 1
48543 2
48543 3
48543 4
48543 5
48543 6
48543 7
48543 8
48543 9
48545 1
48545 2
48545 3
48545 4
48545 5
48545 6
48545 7
48545 8
48545 9
48545 10
48550 1
48550 2
48550 3
48550 4
48550 5
48550 6
48550 7
48550 8
48550 9
48550 10
48565 1
48565 2
48565 3
48565 4
48565 5
48565 6
48565 7
48565 8
48565 9
48565 10
48572 1
48572 2
48572 3
48572 4
48572 5
48572 6
48572 7
48572 8
48572 9
48572 10
48578 1
48578 2
48578 3
48578 4
48578 5
48578 6
48578 7
48578 8
48578 9
48578 10
48580 1
48580 2
48580 3
48580 4
48580 5
48580 6
48580 7
48580 8
48580 9
48580 10
48581 1
48581 2
48581 3
48581 4
48581 5
48581 6
48581 7
48581 8
48581 9
48581 10
48588 1
48588 2
48588 3
48588 4
48588 5
48588 6
48588 7
48588 8
48588 9
48588 10
48593 2
48593 3
48593 4
48593 5
48593 6
48593 7
48593 8
48593 9
48593 10
48595 1
48595 2
48595 3
48595 4
48595 5
48595 6
48595 7
48595 8
48595 9
48595 10
48598 1
48598 2
48598 3
48598 4
48598 5
48598 6
48598 7
48598 8
48598 9
48598 10
48601 1
48601 2
48601 3
48601 4
48601 5
48601 6
48601 7
48601 8
48601 9
48601 10
48604 1
48604 2
48604 3
48604 4
48604 5
48604 6
48604 7
48604 8
48604 9
48604 10
48607 1
48607 2
48607 3
48607 5
48607 6
48607 7
48607 8
48607 9
48607 10
48608 1
48608 2
48608 3
48608 4
48608 5
48608 6
48608 7
48608 8
48608 9
48608 10
48609 1
48609 2
48609 3
48609 4
48609 5
48609 6
48609 7
48609 8
48609 9
48609 10
48615 1
48615 2
48615 3
48615 4
48615 5
48615 6
48615 7
48615 8
48615 9
48615 10
48618 1
48618 2
48618 3
48618 4
48618 5
48618 6
48618 7
48618 8
48618 9
48623 1
48623 2
48623 4
48623 5
48623 6
48623 7
48623 8
48623 9
48623 10
48626 1
48626 2
48626 3
48626 4
48626 5
48626 6
48626 7
48626 8
48626 9
48626 10
48633 1
48633 2
48633 3
48633 4
48633 5
48633 6
48633 7
48633 8
48633 9
48633 10
48648 1
48648 2
48648 3
48648 5
48648 6
48648 7
48648 8
48648 9
48648 10
48683 1
48683 2
48683 3
48683 4
48683 5
48683 6
48683 7
48683 8
48683 9
48683 10
48705 1
48705 2
48705 3
48705 4
48705 5
48705 6
48705 7
48705 8
48705 9
48705 10
48708 1
48708 2
48708 3
48708 4
48708 5
48708 6
48708 7
48708 8
48708 9
48708 10
48710 1
48710 2
48710 3
48710 4
48710 5
48710 6
48710 7
48710 8
48710 9
48710 10
48717 1
48717 2
48717 3
48717 4
48717 5
48717 6
48717 7
48717 8
48717 9
48717 10
48720 1
48720 2
48720 3
48720 5
48720 6
48720 7
48720 8
48720 9
48720 10
48738 1
48738 2
48738 3
48738 4
48738 5
48738 6
48738 7
48738 8
48738 9
48738 10
48813 1
48813 2
48813 3
48813 4
48813 5
48813 6
48813 7
48813 8
48813 9
48813 10
48820 1
48820 2
48820 3
48820 4
48820 5
48820 6
48820 7
48820 8
48820 9
48820 10
48842 1
48842 2
48842 3
48842 4
48842 5
48842 6
48842 7
48842 8
48842 9
48842 10
48854 1
48854 2
48854 3
48854 4
48854 5
48854 6
48854 7
48854 8
48854 9
48854 10
48859 1
48859 2
48859 3
48859 4
48859 5
48859 6
48859 7
48859 8
48859 9
48859 10
48930 1
48930 2
48930 3
48930 4
48930 5
48930 6
48930 7
48930 8
48930 9
48930 10
48932 1
48932 2
48932 3
48932 4
48932 5
48932 6
48932 7
48932 8
48932 9
48932 10
48934 1
48934 2
48934 3
48934 4
48934 5
48934 6
48934 7
48934 8
48934 9
48934 10
48948 1
48948 2
48948 3
48948 4
48948 5
48948 6
48948 7
48948 8
48948 9
48948 10
48951 1
48951 2
48951 3
48951 4
48951 5
48951 6
48951 7
48951 8
48951 9
48951 10
48952 1
48952 2
48952 3
48952 4
48952 5
48952 6
48952 7
48952 8
48952 9
48952 10
48982 1
48982 2
48982 3
48982 4
48982 5
48982 6
48982 7
48982 8
48982 9
48982 10
49024 1
49024 2
49024 3
49024 4
49024 5
49024 6
49024 7
49024 8
49024 9
49024 10
49025 1
49025 2
49025 3
49025 4
49025 5
49025 6
49025 7
49025 8
49025 9
49025 10
49035 1
49035 2
49035 3
49035 4
49035 5
49035 6
49035 7
49035 8
49035 9
49035 10
49040 1
49040 2
49040 3
49040 4
49040 5
49040 6
49040 7
49040 8
49040 9
49040 10
49041 1
49041 2
49041 3
49041 4
49041 5
49041 6
49041 7
49041 8
49041 9
49041 10
49058 1
49058 2
49058 3
49058 4
49058 5
49058 6
49058 7
49058 8
49058 9
49058 10
49061 1
49061 2
49061 3
49061 4
49061 5
49061 6
49061 9
49061 10
49069 1
49069 2
49069 3
49069 4
49069 5
49069 6
49069 7
49069 8
49069 9
49069 10
49074 1
49074 2
49074 3
49074 4
49074 5
49074 6
49074 7
49074 8
49074 9
49074 10
49098 1
49098 2
49098 3
49098 4
49098 5
49098 6
49098 7
49098 8
49098 9
49098 10
49103 1
49103 2
49103 3
49103 4
49103 5
49103 6
49103 7
49103 8
49103 9
49103 10
49111 1
49111 2
49111 3
49111 4
49111 6
49111 7
49111 8
49111 9
49111 10
49187 1
49187 2
49187 3
49187 4
49187 5
49187 6
49187 8
49187 9
49187 10
49216 1
49216 2
49216 3
49216 4
49216 5
49216 6
49216 7
49216 8
49216 9
49216 10
49221 1
49221 2
49221 3
49221 4
49221 5
49221 6
49221 7
49221 8
49221 9
49221 10
49224 1
49224 2
49224 3
49224 5
49224 6
49224 7
49224 8
49224 9
49224 10
49277 1
49277 2
49277 3
49277 4
49277 5
49277 6
49277 7
49277 8
49277 9
49277 10
49279 1
49279 2
49279 3
49279 4
49279 5
49279 6
49279 7
49279 8
49279 9
49279 10

In [ ]:
# combine together to create function to expand df
def expand_df_with_covariates(
    orig_df=pd.DataFrame, path_df=pd.DataFrame,
    all_coco_locs_df=pd.DataFrame
):

    # create all distance matrices
    lvl_dist_matrices = create_distance_matrices(all_coco_locs_df)

    # loop through df and expand
    for i in tqdm(range(0, len(orig_df)-1)):

        # may change this code to loop through subject then level

        # skip last collection in level/subject to avoid predicting collection on
        # following level or subject
        if (orig_df.iloc[i].level != orig_df.iloc[i+1].level) | (
                orig_df.iloc[i].subject != orig_df.iloc[i+1].subject):

            # complete df and write to file
            expanded_df.to_csv(
                '../../data/participant_expansion/exp_for_' +
                str(orig_df.iloc[i].subject) +
                '_lvl_'+str(orig_df.iloc[i].level)+'.csv',
                index=False
            )

            # remove from memory
            del expanded_df

            # do not add data and continue on to next level or subject
            continue

        # set level location distances and arrangement or reset on new level
        if (i == 0) | (orig_df.iloc[i].level != orig_df.iloc[i-1].level) | (orig_df.iloc[i].subject != orig_df.iloc[i-1].subject):

            # code block to set up data for new level

            # reset collection_num
            collect_num = 0

            # use level list to determine locations to consider
            curr_matrix = lvl_dist_matrices[int(orig_df.iloc[i].level-1)]

            # and level arrangement from the locations df
            curr_level_locs = all_coco_locs_df[
                all_coco_locs_df.level == int(orig_df.iloc[i].level)
            ]

            # set available obj list
            avail_obj_indices = [i for i in range(len(curr_level_locs))]

            # index for location df is same
            curr_level_locs.index = avail_obj_indices

            # slice path df
            curr_level_path = path_df[
                (path_df.subject == orig_df.iloc[i].subject) &
                (path_df.level == orig_df.iloc[i].level)
            ]

            # # skip first collection, start expanding for second collection

            # # set heading angle from 0,0 to current location
            # heading_angle = np.atan2(orig_df.iloc[i].y, orig_df.iloc[i].x)

            # # grab obj_ID
            # curr_obj_ID = int(orig_df.iloc[i].obj_ID)

            # ## Covariate calculation ###################################

            # # get distances for available objects
            # dist_from_curr = curr_matrix[curr_obj_ID-1][avail_obj_indices]

            # # neighborhood influenced distance values of available objects
            # nhood_val_from_curr = [
            #     neighborhood_value(obj_ID, curr_matrix, 3, avail_obj_indices) for obj_ID in avail_obj_indices
            # ]

            # # turning angles from current object
            # tas_from_curr = calculate_turning_angles(
            #     heading_angle, curr_obj_ID, curr_level_locs
            # )

            # ## Collection ##############################################
            # collect_df = pd.DataFrame({
            #     'obj_ID': curr_obj_ID,
            #     'time_to_respawn': orig_df.iloc[i].time+5
            # }, index=[0])

            # ## Used/Unused criterion ###################################

            # # set length of expansion
            # rep_len = len(avail_obj_indices)

            # # create used/unused criterion list
            # used_list = [0]*rep_len

            # # set indexed value to one
            # avail_obj_used_index = avail_obj_indices.index(
            #     int(orig_df.iloc[i+1].obj_ID-1)
            # )

            # used_list[avail_obj_used_index] = 1

            # ## Add expanded row ########################################

            # # create expanded df
            # expanded_df = pd.DataFrame({
            #     'strategy': [orig_df.iloc[i].strategy]*rep_len,
            #     'subject': [orig_df.iloc[i].subject]*rep_len,
            #     'level': [orig_df.iloc[i].level]*rep_len,
            #     'collection_num': [collect_num]*rep_len,
            #     'obj_ID': [i+1 for i in avail_obj_indices],
            #     'point_value': [orig_df.iloc[i].point_value]*rep_len,
            #     'distance': dist_from_curr,
            #     'turning_angle': tas_from_curr,
            #     'neighbor_value': nhood_val_from_curr,
            #     'used': used_list,
            #     'time': [orig_df.iloc[i].time]*rep_len
            # })

        else:

            # mark next collection
            collect_num += 1

            # grab previously calculated turning angle from df
            # heading_angle = expanded_df[(expanded_df.collection_num == (
            #     collect_num-1)) & (expanded_df.used == 1)].turning_angle.iloc[0]

            # heading_angle = np.atan2(
            #     orig_df.iloc[i].y-orig_df.iloc[i-1].y,
            #     orig_df.iloc[i].x-orig_df.iloc[i-1].x
            # )

            # grab obj_ID
            curr_obj_ID = int(orig_df.iloc[i].obj_ID)

            # determine obj that are not active by finding -5 or keep
            # the old algorithm with the collect df

            ## Respawning ##############################################
            if len(collect_df) > 0:

                # see if any obj need to respawn
                obj_to_respawn = collect_df[
                    collect_df.time_to_respawn < orig_df.iloc[i+1].time
                ].obj_ID

                # filter out if there is an obj to respawn
                if len(obj_to_respawn) > 0:
                    collect_df = collect_df[
                        collect_df.time_to_respawn > orig_df.iloc[i+1].time
                    ]

                # reset available indices
                avail_obj_indices = [
                    x for x in [i for i in range(len(curr_matrix))] if x not in collect_df.obj_ID.values-1
                ]

            ## Covariate calculation ###################################

            # get distances for available objects
            dist_from_curr = curr_matrix[curr_obj_ID-1][avail_obj_indices]

            # neighborhood influenced distance values of available objects
            nhood_val_from_curr = [
                neighborhood_value(obj_ID, curr_matrix, 2, avail_obj_indices) for obj_ID in avail_obj_indices
            ]

            # turning angles from current object
            tas_from_curr = calculate_turning_angles(
                heading_angle, curr_obj_ID, curr_level_locs
            )

            # filter for only available obj
            tas_from_curr = [
                tas_from_curr[i] for i in avail_obj_indices
            ]

            ## Collection ##############################################

            # add new row
            collect_df.loc[len(collect_df)] = [
                curr_obj_ID, orig_df.iloc[i].time+5]

            ## Used/Unused criterion ###################################

            # set length of expansion
            rep_len = len(avail_obj_indices)

            used_list = [0]*rep_len

            # set indexed value to one
            avail_obj_used_index = avail_obj_indices.index(
                int(orig_df.iloc[i+1].obj_ID-1))
            used_list[avail_obj_used_index] = 1

            ## Add expanded row ########################################
            row_expansion = pd.DataFrame({
                'strategy': [orig_df.iloc[i].strategy]*rep_len,
                'subject': [orig_df.iloc[i].subject]*rep_len,
                'level': [orig_df.iloc[i].level]*rep_len,
                'collection_num': [collect_num]*rep_len,
                'obj_ID': [i+1 for i in avail_obj_indices],
                'point_value': [orig_df.iloc[i].point_value]*rep_len,
                'distance': dist_from_curr,
                'turning_angle': tas_from_curr,
                'neighbor_value': nhood_val_from_curr,
                'used': used_list,
                'time': [orig_df.iloc[i].time]*rep_len
            })

            # add to the new expanded df
            expanded_df = pd.concat(
                [expanded_df, row_expansion], ignore_index=True
            )

    # finish and return
    return expanded_df

In [ ]:
# run the expansion
# expanded_df = expand_df_with_covariates(
#     orig_df=player_forages, all_coco_locs_df=all_lvls_coco_locs
# )

  1%|▏         | 3218/245189 [00:20<25:14, 159.80it/s]

ValueError: 56 is not in list

In [48]:
expanded_df

,strategy,forager,level,collection_num,obj_ID,point_value,distance,turning_angle,neighbor_value,used,time
0,nn,17,1,0,1,2.0,33.871079,2.208034,0.285714,0,1.229751
1,nn,17,1,0,2,2.0,30.413813,2.191046,0.285714,0,1.229751
2,nn,17,1,0,3,2.0,30.000000,2.356194,0.285714,0,1.229751
3,nn,17,1,0,4,2.0,31.622777,2.034444,0.282843,0,1.229751
4,nn,17,1,0,5,2.0,27.613403,2.265535,0.282843,0,1.229751
...,...,...,...,...,...,...,...,...,...,...,...
37214,nn,17,3,3,64,4.0,46.097722,-7.930754,0.282843,0,2.152064
37215,nn,17,3,3,65,4.0,38.890873,-7.853982,0.282843,0,2.152064
37216,nn,17,3,3,66,4.0,42.573466,-7.937123,0.282843,0,2.152064
37217,nn,17,3,3,67,4.0,46.502688,-8.006631,0.285714,0,2.152064
37218,nn,17,3,3,68,4.0,40.401114,-8.003304,0.282843,0,2.152064

In [44]:
expanded_df[expanded_df.used == 1].obj_ID

28       29
91       25
156      24
217      20
283      22
         ..
36950    66
36964    12
37028     9
37091     6
37154     4
Name: obj_ID, Length: 654, dtype: object

In [45]:
expanded_df.groupby(['level', 'collection_num']).count()

                      strategy  forager  obj_ID  point_value  distance  \
level collection_num
1     0                     68       68      68           68        68
      1                     67       67      67           67        67
      2                     66       66      66           66        66
      3                     65       65      65           65        65
      4                     64       64      64           64        64
...                        ...      ...     ...          ...       ...
2     300                   57       57      57           57        57
3     0                     68       68      68           68        68
      1                     67       67      67           67        67
      2                     66       66      66           66        66
      3                     65       65      65           65        65

                      turning_angle  neighbor_value  used  time
level collection_num
1     0                          67              68    68    68
      1                          66              67    67    67
      2                          65              66    66    66
      3                          64              65    65    65
      4                          63              64    64    64
...                             ...             ...   ...   ...
2     300                        56              57    57    57
3     0                          67              68    68    68
      1                          66              67    67    67
      2                          65              66    66    66
      3                          64              65    65    65

[654 rows x 9 columns]

In [ ]:
expanded_df.to_csv(
    '../../data/simulation/expanded_simul_w_cov_10_16_25.csv', index=False)