#### Creating data for sequential choice models
The series of models I plan to use in my thesis project, inspired by habitat-selection functions from movement ecology, use environmental covariates of available resources (e.g., distance from current location, turning angle from previous bearing angle, size/point value, etc.) to predict whether a resource will be chosen next. By specifying a series of models containing different parameters, I will fit different cognitive heuristic strategies to human sequential choice data and determine parameters of significance to the foraging strategies of participants.

To start, I must take existing foraging data in the form of logs of collected objects during play and expand it out to include the covariates of interest of all available objects. This data needs to also reflect the removal and reintroduction of collected objects during the course of play.

In [96]:
# import libraries
import pandas as pd
import numpy as np
from tqdm import tqdm
import os

In [ ]:
# read in simulation results
player_paths = pd.read_csv(
    '../../data/clean_datasets/clean_location_data.csv'
)

player_forages = pd.read_csv(
    '../../data/clean_datasets/imputed_forage_data.csv'
)

# arrange location data and forage data
player_paths = player_paths.groupby('subject').sort_values('time')

# clean up
# reset index
player_paths.index = [*range(len(player_paths))]
player_forages.index = [*range(len(player_forages))]

# subset cols, remove old x and y and rename imputed x,y to x,y
player_forages = player_forages.iloc[:, [*range(0, 4), *range(6, 9)]]

player_forages.rename(columns={
    'new_x': 'x',
    'new_y': 'y'
}, inplace=True)

# read in obj locs
all_lvls_coco_locs = pd.read_csv(
    '../../data/level_arrangements/all_levels_arrangements.csv'
)

AttributeError: 'DataFrameGroupBy' object has no attribute 'sort_values'

In [123]:
player_paths.groupby(['subject', 'level']).min('time')

                       x          y  rotation         time
subject level
46986   1     -23.759850 -25.787161         0  1537.185059
        2     -30.000000 -30.000000         0  1733.873047
        3     -25.345381 -25.381760         0  1868.189941
        4     -30.000000 -28.290779         0  1002.690979
        5     -30.000000 -26.067909         0   543.027527
...                  ...        ...       ...          ...
49279   6     -13.973570 -22.574570         0   417.123901
        7     -23.472710 -25.028151         0   938.541321
        8     -14.803500 -19.930799         0  1070.360962
        9     -30.000000 -19.216141         0   650.156372
        10     -8.803991 -20.728519         0   130.587997

[859 rows x 4 columns]

In [114]:
player_forages.head()

   subject  level  obj_ID  point_value     x     y         time
0    46986      1      58            2  -6.5 -15.0  1542.796997
1    46986      1      59            2 -10.0 -15.0  1543.081055
2    46986      1      56            2 -12.5 -17.5  1543.463989
3    46986      1      60            2 -15.0 -15.0  1543.496948
4    46986      1      53            2 -15.0 -20.0  1543.729004

##### Adding covariates and all available objects
The two covariates of interest needed to be added to this expanded data set are distance from current location and turning angle

In [ ]:
# distance matrices store distances between coconuts
def create_distance_matrices(obj_locs=pd.DataFrame):

    # create list for levels
    dist_matrix_list = []

    # for each level, create matrix of all distances
    for level in range(0, 10):
        # filter for this level
        level_locs = obj_locs[obj_locs.level == level+1]

        # reset index for consistent indexing
        level_locs.index = [*range(0, len(level_locs))]

        # create empty matrix
        level_m = np.zeros((len(level_locs), len(level_locs)), dtype=float)

        # fill this level's matrix
        for i in range(0, len(level_locs)):
            for j in range(0, len(level_locs)):
                # check if same location
                if i == j:
                    level_m[i, j] = 0  # set to zero, save computation
                else:
                    # calc distance and store in matrix
                    level_m[i, j] = np.sqrt(
                        np.pow(level_locs.x[i]-level_locs.x[j], 2) +
                        np.pow(level_locs.y[i]-level_locs.y[j], 2)
                    )

        # add to list
        dist_matrix_list.append(level_m)

    return dist_matrix_list


d = create_distance_matrices(all_lvls_coco_locs)

In [99]:
# grouped function to find both ta and distances of alternatives
def find_turning_angles_and_distances(
    path_slice=pd.DataFrame, lvl_coco_locs=pd.DataFrame
):

    # find the heading angle

    # # slice the path df before collection time
    # path_slice = path_df[path_df.time <= collection_time].tail(n=2)

    # get heading angle
    heading_angle = np.atan2(
        path_slice.iloc[1].y - path_slice.iloc[0].y,
        path_slice.iloc[1].x - path_slice.iloc[0].x
    )

    # find turning angles to available obj
    # empty list for angles
    ta_list = [
        np.atan2(
            lvl_coco_locs.iloc[coco-1].y -
            path_slice.iloc[1].y,
            lvl_coco_locs.iloc[coco-1].x -
            path_slice.iloc[1].x
        ) - heading_angle for coco in lvl_coco_locs.obj_ID
    ]

    # find the distances
    dist_list = [
        np.sqrt(
            np.pow(lvl_coco_locs.iloc[coco-1].y -
                   path_slice.iloc[1].y, 2) +
            np.pow(lvl_coco_locs.iloc[coco-1].x -
                   path_slice.iloc[1].x, 2)
        ) for coco in lvl_coco_locs.obj_ID
    ]

    return ta_list, dist_list

In [ ]:
# neighbors distance
def neighborhood_value(
    curr_coco_ind=int, lvl_dist_matrix=list, num_neighbors=int, avail_indices=list
):
    # filter the df for currently available obj and their distances from focal obj
    active_obj_dists = [lvl_dist_matrix[curr_coco_ind][i]
                        for i in avail_indices]

    return np.sum(np.reciprocal(sorted(active_obj_dists)[1:num_neighbors+1]))

In [119]:
player_paths[(player_paths.subject == 47835) & (player_paths.level == 4)]

         subject  level          x          y  rotation         time
1122313    47835      4  11.741160  13.569450       302   891.443970
1122314    47835      4  10.348590  13.879780       273   891.561218
1122315    47835      4   9.150119  13.916000       276   891.677673
1122316    47835      4   7.788713  14.368190       297   891.794617
1122317    47835      4  12.949340  11.617420       357   891.243225
...          ...    ...        ...        ...       ...          ...
1123322    47835      4  17.955000  20.397591       207  1003.760986
1123323    47835      4  17.955000  20.397591       207  1003.877014
1123324    47835      4  17.955000  20.397591       207  1003.994019
1123325    47835      4  17.955000  20.397591       207  1004.093994
1123326    47835      4  17.955000  20.397591       207  1004.193970

[1014 rows x 6 columns]

In [117]:
# loop through subjects and levels and expand their data

for subject in tqdm(player_forages.subject.unique()):

    # some subjects may not have had all levels, get their unique levels
    lvls = player_forages[player_forages.subject == subject].level.unique()

    # loop through their levels
    for lvl in lvls:

        # subset forage data, path data, matrices, coco locations
        s_forage = player_forages[(player_forages.subject == subject) & (
            player_forages.level == lvl)]
        s_path = player_paths[(player_paths.subject == subject) & (
            player_paths.level == lvl)]
        s_matrix = d[lvl-1]
        s_locs = all_lvls_coco_locs[all_lvls_coco_locs.level == lvl]

        # reset indices for proper subsetting
        s_forage.index = [i for i in range(len(s_forage))]
        s_path.index = [i for i in range(len(s_path))]
        s_locs.index = [i for i in range(len(s_locs))]

        # set file string to create or append file
        file_string = '../../data/participant_expansion/exp_for_' + \
            str(subject) + '_lvl_' + str(lvl) + '.csv'

        # loop through collections
        for row_num in range(len(s_forage)-1):

            # slice that row and expand
            s_row = s_forage.iloc[row_num]

            # get path data prior to collection, prior collection point (pcp)
            pcp = s_path[s_path.time <= s_row.time].tail(n=2)

            # find unavailable cocos by subsetting df to only include obs
            # within the last 5 seconds
            unavail_ids = [
                id for id in s_forage[(s_forage.time >= s_row.time - 5) & (s_forage.time <= s_row.time)].obj_ID
            ]

            # subset ids into list of available indices

            avail_indices = [
                id for id in [i for i in range(len(s_matrix))] if id not in [j-1 for j in unavail_ids]
            ]

            # print(avail_indices)
            # print(unavail_ids)
            # print(s_row)

            # find ta and distance and cluster values
            tas, dists = find_turning_angles_and_distances(pcp, s_locs)

            clsts = [
                neighborhood_value(i, s_matrix, 3, avail_indices) for i in avail_indices
            ]

            # subset covariates aside from clst for only available obj
            tas = [tas[i] for i in avail_indices]
            dists = [dists[i] for i in avail_indices]
            pvs = [int(s_locs.iloc[i].point_value) for i in avail_indices]

            # find used coco from next collection
            used_list = [0 if i != s_forage.iloc[row_num +
                                                 1].obj_ID-1 else 1 for i in avail_indices]

            # stow length of expanded slice
            rep_len = len(avail_indices)

            # add expanded row to file
            exp_df = pd.DataFrame({
                'subject': [s_row.subject]*rep_len,
                'level': [s_row.level]*rep_len,
                'collection_num': [row_num+1]*rep_len,
                'obj_ID': [i+1 for i in avail_indices],
                'point_value': pvs,
                'distance': dists,
                'turning_angle': tas,
                'neighbor_value': clsts,
                'used': used_list,
                'time': [s_row.time]*rep_len
            })

            exp_df.to_csv(
                file_string,
                mode='a',  # append
                # add header if new file
                header=not os.path.exists(file_string),
                index=False  # no index col
            )

  5%|▍         | 4/87 [02:29<51:46, 37.42s/it]

IndexError: single positional indexer is out-of-bounds